# These service definitions depend on $CDX_ vars as defined by cdx-env-tools/vyrc

version: '3.2'
services:
  redis: # https://hub.docker.com/_/redis
    image: 'redis:6.0.3'
    command: redis-server --requirepass redis123
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  activemq: # https://hub.docker.com/r/webcenter/activemq
    image: 'webcenter/activemq:5.14.3'
    environment:
      ACTIVEMQ_ADMIN_LOGIN:    'mqAdmin'
      ACTIVEMQ_ADMIN_PASSWORD: 'mqAdmin123'
    ports:
      - '61613:61613'
      - '61616:61616'
      - '8161:8161'

  sftp: # https://hub.docker.com/r/atmoz/sftp
    image: atmoz/sftp
    volumes:
      - ${CDX_CONFIGS}/sftp/sshd:/etc/ssh/
      - ${CDX_CONFIGS}/sftp/ssh/sftp_cdx_rsa.pub:/home/cdx/.ssh/keys/id_rsa.pub:ro
      # un-comment to persist ftp storage outside the container
      #- ${CDX_STORAGE}/sftp/nerp:/home/cdx/nerp
    ports:
      - "2222:22"
    # user:pass[:e][:uid[:gid[:dir1[,dir2]...]]]
    command: cdx::::nerp,nerp/toCFMS,nerp/toNavyERP

  s3: # https://hub.docker.com/r/minio/minio/
    image: minio/minio:RELEASE.2021-05-18T00-53-28Z
    # un-comment to persist s3 storage outside the container
    volumes:
      - ${CDX_STORAGE}/s3:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: cfms
      MINIO_SECRET_KEY: cfms1234
    command: server /data

  wiremock: # https://github.com/rodolpheche/wiremock-docker
    image: 'rodolpheche/wiremock:2.25.1'
    ports:
      - '8643:443'
      - '8680:8080'
    volumes:
      - ${CDX_CONFIGS}/pki:/home/pki
      - ${CDX_DATA}/wiremock:/home/wiremock
    command: >
      --https-port 443
        --https-keystore /home/pki/wiremock_keystore.jks
        --keystore-password wmKeyStore123
      --https-require-client-cert
        --https-truststore /home/pki/wiremock_cacerts.jks
        --truststore-password wmTrustStore123
