# These service definitions depend on $CDX_ vars as defined by cdx-env-tools/cdxrc

version: '3.2'
services:
  oracle: # https://github.com/oracle/docker-images.git
    build:
      context: ${CDX_PROJECTS}/oracle/docker-images/OracleDatabase/SingleInstance/dockerfiles/18.4.0
      dockerfile: Dockerfile.xe
      args:
        DB_EDITION: xe
    image: oracle/database:18.4.0-xe
    shm_size: 1G
    ports:
      - '1521:1521'
    #  - '5500:5500'  # https://localhost:5500/em/            (OEM Express)
    #  - '8180:8080'  # http://localhost:8180/apex/apex_admin (Oracle Application Express)
    volumes:
      - ${CDX_STORAGE}/oracle/oradata:/opt/oracle/oradata:rw
    environment:
      ORACLE_EDITION: XE
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_SID: XE
      ORACLE_PWD: oraPassword123  # for SYS, SYSTEM, PDB_ADMIN
